build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - "(453) 392-4829"
    - "(236) 203-0384"